#!/usr/bin/env bash
# A Bash script that will display information about the subdomains
get_dns_info() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain")
        if [ -n "$result" ]; then
            record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
            echo "The subdomain $sub is a $record_type record and points to $result"
        fi
    done
}

get_dns_info "$1" "$2"

