#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=0
end=13

while [ $i -lt $end ]; do
	echo "Hour: $i"

	if [ $i -eq 12 ]; then
		exit
	fi

	j=1
	while [ $j -lt 60 ]; do
		echo "$j"
		((j++))
	done

	((i++))
done
