#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for ((i=0; i<=12; i++)); do
	echo "Hour: $i"
	if [ $i == 12 ]; then
		exit
	fi
	for ((j=1; j<60; j++)); do
		echo "$j"
	done
done

